export enum EInputOptionsTypes {
  INPUT_TEXT = 'INPUT_TEXT',
  INPUT_EMAIL = 'INPUT_EMAIL',
  INPUT_DATE = 'INPUT_DATE',
  INPUT_DATETIME = 'INPUT_DATETIME',
  INPUT_CALENDAR = 'INPUT_CALENDAR',
  INPUT_BUTTONS = 'INPUT_BUTTONS',
  INPUT_SELECT = 'INPUT_SELECT',
  INPUT_CHECKBOX = 'INPUT_CHECKBOX',
  INPUT_RADIO = 'INPUT_RADIO',
  INPUT_RANGE = 'INPUT_RANGE',
  INPUT_ICON = 'INPUT_ICON',
  INPUT_UPLOAD = 'INPUT_UPLOAD'
}
